### ISSUE TITLE
Inquiry Regarding Index File for mod_system_no_mol.top

### ISSUE THREAD

**Issue by AzraelXu** [Dead-fisher/FEP_files#1]
Dear Yanze,

I hope this message finds you well. I have a quick question regarding the mod_system_no_mol.top file that you provided. As I understand, this file was generated using AMBERTOOL.

My inquiry pertains to the configuration file (config.ini) where the following line is specified:

![image](https://github.com/yanze039/FEP_files/assets/71536738/bb5e10be-f7a7-4756-bb86-da9e287b3830)

Could you kindly provide some insights into how this index file was generated? I'm particularly interested in understanding the methodology behind its creation.

Additionally, as I am relatively new to Free Energy Perturbation (FEP), could you also provide the relevant commands used in AMBERTOOL to generate the mod_system_no_mol.top file? Any guidance or resources you could offer would be greatly appreciated.

Thank you in advance for your assistance. I look forward to hearing from you soon.

Best regards,

Xu

**Comment by yanze039** [comment]
Hi Xu,

This repo and these files were for test of `PyAutoFEP` and no longer used anyway. Since there are too many unsolved bugs in `PyAutoFEP` and its inactive maintaince and dev, I've just gave it a try and never used it for any production calculations (also I already can't really remember how it was setup).

Sorry for this inconvenience, but I would recommend you switch to gromacs official documents to understand how gromacs dealing with fep calculations. Gromacs uses single topology inheritly and typically the alchemical changes are built by the single topology protocol.  In gromacs, what we usually did is to build alchemical topology by common core matching (via `rdkit`). Then we would change this topology parameters by `parmed` or other package you can play with. 

`ambertools` can't generate `top` files directly for flexible cases, you may build your system in amber format and convet them to whatever you want by `parmed`.

If you are not very familiar with FEP, I would also recommend `amber22` TI for alchemical free energy calculations as they provide more detailed tutorials with GPU accelerations (also free since last year). They essentially are the same, but amber22 has much easier setting up for beginners. You may also refer to Darrin York's papers realting to Amber TI and ACES.

**Comment by AzraelXu** [comment]
Dear Yanze,

Thank you very much for your prompt response. I will proceed to look into the use of AMBERTI. I wish you all the best in your endeavors.

Best regards,

Xu
